backend:
name: github
repo: "ev-tours"
branch: main
auth: github
apiHost: https://api.github.com
login:
  url: https://evtours.com.au/.netlify/functions/auth/authorize
  callbackUrl: https://evtours.com.au/.netlify/functions/auth/callback
