backend:
  name: github
  repo: ev-tours/website
  branch: main
  auth: github
  api_root: https://api.github.com

  login:
    url: https://evtours.com.au/.netlify/functions/auth/authorize
    callback_url: https://evtours.com.au/.netlify/functions/auth/callback
